vich_uploader:
    db_driver: orm
    mappings:
        plat_image:
            uri_prefix: /uploads/plats
            upload_destination: "%kernel.project_dir%/public/uploads/plats"

        drink_image:
            uri_prefix: /uploads/drinks
            upload_destination: "%kernel.project_dir%/public/uploads/drinks"
        extra_image:
            uri_prefix: /uploads/extras
            upload_destination: "%kernel.project_dir%/public/uploads/extras"
